src/Entity/Product.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Cocur\Slugify\Slugify;

/**
 * @ORM\Entity(repositoryClass="App\Repository\ProductRepository")
 */
class Product
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $description;

    /**
     * @ORM\Column(type="float")
     */
    private $prix;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public  function getSlug(): string
    {
        return (new Slugify())->slugify($this->nom);
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getFormatPrice(): string
    {

        return number_format($this->prix, 0, '', '.');
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class DefaultController extends AbstractController
{
    /**
     * @Route("/login")
     */
    public function admin(): Response
    {
        return new Response('<html><body>Admin page!</body></html>');
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class HomeController extends AbstractController {

    /**
     * @Route("/", name="home")
     * @return Response
     */

    public function index(): Response
    {

      return $this->render('pages/home.html.twig');

    }

}

src/Controller/PanierController.php
<?php

namespace App\Controller;

use App\Repository\ProductRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Session\SessionInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;



class PanierController extends AbstractController {


    /**
     * @var ProductRepository
     */
    private $repository;

    /**
     * @param ProductRepository $repository
     */


    public function __construct(ProductRepository $repository)
    {
        $this->repository = $repository;

    }


    /**
     * @param Request $request
     * @return Response
     */
    public  function nbArticle(Request $request)
    {
        $session = $request->getSession();
        if (!$session->has('panier'))
            $articles = 0;
        else
            $articles = count($session->get('panier'));


        return $this->render('panier/boutonPanier/boutonPanier.html.twig',[
            "articles" => $articles
        ]);



    }

    /**
     * @Route("/suppimer/{id}", name="panier.suppArticle")
     * @param SessionInterface $session
     * @param $id
     * @return Response
     */

    public function supprimerArticle(SessionInterface $session, $id)
    {
        $panier = $session->get('panier');

        if (array_key_exists($id, $panier))
        {
            unset($panier[$id]);
            $session->set('panier', $panier);
            $this->addFlash('danger', 'Article supprimé avec succès !');
        }

        return $this->redirect($this->generateUrl('panier'));

    }



    /**
     * @Route("/suppimer", name="panier.supprime")
     * @param Request $request
     * @return Response
     */

    public function supprimer(Request $request): Response
    {
        $session = $request->getSession();
        $session->clear();
        $session->set('panier', array());

        return $this->redirect($this->generateUrl('panier'));

    }


    /**
     * @Route("/ajouter/{id}", name="panier.ajout")
     * @param SessionInterface $session
     * @param Request $request
     * @param $id
     * @return Response
     */

    public function ajouter(SessionInterface $session, Request $request, $id)
    {


        if (!$session->has('panier'))
            $session->set('panier', array());
            $panier = $session->get('panier');

        if (array_key_exists($id, $panier)) {

            if ($request->query->get('qte') != null)

                $panier[$id] = $request->query->get('qte');
        } else {
            if ($request->query->get('qte') != null)
                $panier[$id] = $request->query->get('qte');
            else
                $panier[$id] = 1;
            $this->addFlash('success', 'Article ajouté avec succès !');

        }

        $session->set('panier', $panier);


        return $this->redirect($this->generateUrl('panier'));
    }

    /**
     * @Route("/panier}", name="panier")
     * @param Request $request
     * @return Response
     */

    public function index(Request $request): Response
    {
        $session = $request->getSession();

        $product = $this->repository->findArray(array_keys($session->get('panier')));

        if (!$session->has('panier')) $session->set('panier', array());

        return $this->render('panier/panier.html.twig',[
            "products" => $product,
            "panier" => $session->get('panier')
        ]);
    }

}

src/Controller/ProductController.php
<?php

namespace App\Controller;

use App\Entity\Product;
use App\Repository\ProductRepository;
use Doctrine\Common\Persistence\ObjectManager;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;


class ProductController extends AbstractController {


    /**
     * @var ProductRepository
     */
    private $repository;
    /**
     * @var ObjectManager
     */
    private $em;

    public function __construct(ProductRepository $repository, ObjectManager $em)
     {
         $this->repository = $repository;
         $this->em = $em;
     }

    /**
     * @Route("/produits", name="product.index" )
     * @return Response
     */
    public function index(PaginatorInterface $paginator, Request $request):Response
    {
      $product = $paginator->paginate(
          $this->repository->findAllByNameAscQuery(),
          $request->query->getInt('page', 1),
          4
          );

      return $this->render('product/index.html.twig',[
          "Current_menu" => "products",
          "products" => $product,
      ]);

    }

    /**
     * @Route("/produits/{slug}-{id}", name="product.show", requirements={"slug": "[a-z0-9\-]*"})
     * @param Product $product
     * @return Response
     */
    public function show(Product $product, string $slug):Response
    {
        if ($product->getSlug() !== $slug)
        {
           return $this->redirectToRoute('product.show', [
                'id'   => $product->getId(),
                'slug' => $product->getSlug()
            ], 301);
        }
        return $this->render('product/show.html.twig',[
            "product" => $product,
            "Current_menu" => "products"
        ]);

    }


    /**
     * @Route("/export", name="product.export" )
     * @return Response
     */
    public function export()
    {
        $events  = $this->repository->findAll();
        $rows = array();
        foreach ($events as $event) {
            $data = array($event->getId(), $event->getNom(), $event->getDescription(), $event->getPrix());
            $rows[] = implode(',', $data);
        }
        $content = implode("\n", $rows);
        $response = new Response($content);
        $response->headers->set('Content-Type', 'text/csv');
        $response->headers->set('Content-Disposition', 'attachment; filename="produits.csv"');
        return $response;
    }

}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        {% block stylesheets %}
            <link rel="stylesheet" href="{{ asset('build/app.css') }}" >
        {% endblock %}
    </head>
    <body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="{{ path('home') }}">ChoosIt</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link {% if Current_menu is defined and Current_menu == 'products' %}active{% endif %}" href="{{ path('product.index') }}">Catalogue</a>
                </li>

            </ul>
            {{ render(controller('App\\Controller\\PanierController::nbArticle')) }}

                </div>
    </nav>
        {% block body %}{% endblock %}

        {% block javascripts %}

            <script src="{{ asset('build/app.js') }}"></script>
        {% endblock %}
    </body>
</html>

templates/pages/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}ChoosIt{% endblock %}

{% block body %}
    <div class="text-center">
        <img  class="image-style" src="{{ asset("images/d product 8.jpg")}}" height="200" alt="choosit" />
    </div>
    <div class="jumbotron text-center">
    <p>Choosit agence digital depuis 1998 - Création de site internet responsive à Montpellier. Expert Drupal, Prestashop et Wordpress.</p>
    </div>

{% endblock %}

templates/panier/boutonPanier/boutonPanier.html.twig
<a  {% if articles != 0 %} class="btn btn-success"  {% else %} class="btn btn-light" {% endif %} role="button" href="{{ path('panier') }}"><i class="fas fa-shopping-cart"></i> Votre Panier
    <span class="badge badge-light">
        {% if articles == 0 %}
        0
        {% else %}
        {{ articles }}
        {% endif %}
    </span>
</a>

templates/panier/panier.html.twig
{% extends 'base.html.twig.' %}

{% block title  %}Panier{% endblock %}

{% block body %}
    <div class="container mt-3">

        <h2>Mon panier</h2>
        <div class="col-md-10">
            {% for type, flash_messages in app.session.flashBag.all %}
                {% for msg in flash_messages %}
                    <div class="alert alert-{{ type }}">
                        {{ msg }}
                    </div>
                {% endfor %}
            {% endfor %}
        <table class="table table-striped table-hover" width="100%">
            <thead>
            <tr>
                <th>Références</th>
                <th>Nom</th>
                <th></th>
                <th>Quantité</th>
                <th>PrixUT</th>
                <th>Total</th>
            </tr>
            </thead>
            <tbody>
            {% if  products | length == 0  %}
            <tr>
                <td colspan="6" class="text-center">Panier est vide</td>
            </tr>
            {% endif %}
            {% set somme = 0 %}
            {% for product in products  %}
            <form  action="{{ path('panier.ajout',{"id": product.id}) }}"  method="get">
                <tr>
                    <td>{{ product.id }}</td>
                    <td>{{ product.nom }}</td>
                    <td>
                        <img  class="image-style-thumb" src="{{ asset("images/") ~ product.nom }}.jpg" height="40" alt="{{ product.nom }}" />
                    </td>
                    <td class="form-inline">
                        {{ panier[product.id] }}&nbsp;
                         <input class="form-control" type="number" style="width: 30%" max="99" min="1" name="qte" onchange="this.form.submit()"/>
                        &nbsp;<a href="{{ path('panier.suppArticle',{"id": product.id}) }}"><i  class="fa fa-trash"></i></a>
                    </td>
                    <td>{{ product.getFormatPrice }} €</td>
                    <td>{{ (product.prix * panier[product.id])|number_format(0, '', '.') }} €</td>
                </tr>
            {% set somme = somme + product.prix * panier[product.id] %}
            </form>
            {% endfor %}
            </tbody>
            <tfoot>
            <tr>
                <th colspan="5" class="text-right">Total Commande:</th>
                <th> {{ somme|number_format(0, '', '.') }} €</th>
            </tr>
            </tfoot>

        </table>
            <p class="card-text">
                <a class="btn btn-primary" role="button"  href="{{ path('panier.supprime') }}">Vider le panier</a>
            </p>
    </div>
        <div class="col-md-4"></div>
    </div>

{% endblock %}

templates/product/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Catalogue de Produits{% endblock %}

{% block body %}
    <div class="container mt-4">
        <h3>Catalogue de Produits</h3>
        <p class="card-text">
            <a class="btn btn-primary" role="button"  href="{{ path('product.export') }}">Exporter Les produit CSV</a>
        </p>
    <div class="row flex">
            {% for product in products %}
                {% include('product/produit.html.twig') %}
            {% endfor %}
        <div class="navigation navigator-center">
            {{ knp_pagination_render(products) }}
        </div>

    </div>
    </div>

{% endblock %}

templates/product/produit.html.twig
<div class="col-3">
    <div class="car text-center" >
        <div style="border-style: groove;background-color: white" >
            <img  class="image-style" src="{{ asset("images/") ~ product.nom }}.jpg" height="200" alt="{{ product.nom }}" />
            <div class="card-body" style="background-color: #F5F5F5">
                <h5 class="card-title">
                    <a id="produits" href="#">{{ product.nom }}</a>
                </h5>
                <p class="card-text">
                    {{ product.description}}
                </p>
                <div class="text-danger" style="font-size: 2em">{{ product.getFormatPrice }} €</div>
                <p class="card-text">
                    <a class="btn btn-primary" role="button"  href="{{ path('product.show', {id: product.id , slug: product.slug}) }}">Details...</a>
                </p>
            </div>
        </div>
    </div></br>
</div>

templates/product/show.html.twig
{% extends 'base.html.twig' %}

{% block title product.nom  %}

{% block body %}
    <div class="container mt-3" style="border-style: groove;background-color: white">
        <div class="row justify-content-between">
            <div class="col-md-2">
    <img  class="image-style" src="{{ asset("images/") ~ product.nom }}.jpg" height="200" alt="{{ product.nom }}" />
            </div>
            <div class="col-md-8">
                <h3>{{ product.nom }}</h3>
                <h5>Carateristiques:</h5>
                <p>{{ product.description  | nl2br  }}</p>

            </div>
            <div class="col-md-2" style="border: 1px solid #d7d9e4;padding: 10px 10px;text-align: center;">
                <div class="car">
                    <div class="card-body">
                        <h5 class="card-title" style="color: red">
                            {{ product.formatPrice }} €
                        </h5>
                        <p class="card-text">
                            <form action="{{ path('panier.ajout', {'id': product.id}) }}" method="get">
                        Quantité <input  type="number" style="width: 30%" max="99" min="1" name="qte"/>
                        </p>
                        <p class="card-text">
                            <button class="btn btn-success btn-lg" >Au panier!</button>
                        </p>
                        </form>
                    </div>
                </div>
            </div>
        </div>

    </div>

{% endblock %}